const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const {stripTypeScriptTypes}=require('module');
const root=process.cwd(),tmp=fs.mkdtempSync('/tmp/a17-r6-');
function src(f){return fs.readFileSync(path.join(root,f),'utf8')}
function strip(s){return stripTypeScriptTypes(s).replace(/^import .*;\s*$/mg,'').replace(/\bexport /g,'')}
let l=strip(src('src/server/lanes.ts')); l=l.replace(/function assertWriter\(\)\s*\{[\s\S]*?\n\}/,'function assertWriter() {}');
const ctx=vm.createContext({fs,path,net:{},createHash:crypto.createHash,randomBytes:crypto.randomBytes,process,Buffer,console,dataDir:()=>tmp,ensureDir:p=>fs.mkdirSync(p,{recursive:true}),writeAtomic:(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)}});
vm.runInContext(l,ctx);const lanes={};for(const m of l.matchAll(/function (\w+)\(/g))lanes[m[1]]=ctx[m[1]]; Object.assign(lanes,{GROUP_CLOSE_TTL_MS:300000,HELD_STARVATION_MS:300000});
const dc=vm.createContext({lanes,crypto,Buffer,console});vm.runInContext(strip(src('src/server/lane-drain.ts')),dc);
function add(g,id,open=false){lanes.recordDispatch({groupId:g,groupOpen:open,groupSize:2,label:id,charter:'qa',provider:'qa',transport:'socket'},id);lanes.settle(id,{state:'settled',resultText:'RESULT '+id})}

add('closed','a',true);lanes.closeGroup('closed');const first=dc.process(['group:closed']);dc.acknowledge(['a'],first.receipt);const pre=lanes.groupState('closed');lanes.openGroup('closed',{members:[{label:'b',charter:'qa',provider:'qa',transport:'socket',state:'running'}]});const b=lanes.readAll().find(r=>r.label==='b');lanes.settle(b.id,{state:'settled',resultText:'SECOND'});lanes.closeGroup('closed');const second=dc.process(['group:closed']);assert.equal(second.lanes.length,1);console.log('1 closed+drained seal='+pre.sealedKind+' reopen=accepted secondDrain='+second.lanes.length);
add('open','o',true);dc.process(['lane:o']);console.log('1 readiness terminal='+dc.groupTerminal('open').terminal+' pending='+JSON.stringify(dc.pending().filter(x=>x.groupId==='open').map(x=>({kind:x.kind,ready:x.ready}))));
const cs=src('src/server/dispatch-client.mjs');let receipt;const cc=vm.createContext({Buffer,crypto,fs:{writeSync:(fd,b,o,n)=>n??b.length},process:{exit(){}},setTimeout:()=>({unref(){}})});vm.runInContext(cs.slice(cs.indexOf('function writeAllSync('),cs.indexOf('function unavailable(')),cc);
let matches=0;for(const ok of [true,false])for(const text of ['abc',':12:','文🙂','']){receipt=null;cc.ackAndExit({write(s,cb){receipt=JSON.parse(s);cb()},end(){}},{ok,text,receiptNonce:'a'.repeat(32)});const expected=lanes.receiptDigest('a'.repeat(32),ok?'fd1':'fd2',Buffer.from(text));if(receipt.digest===expected)matches++;else console.log('2 mismatch ok='+ok+' text='+JSON.stringify(text));}console.log('2 peerMatches='+matches+'/8');
for(const [a,b,c,d] of [['a','bc','ab','c'],['a:','b', 'a',':b'],['文','🙂','文🙂',''],['','12:', '12',' :']])assert.notEqual(lanes.receiptDigest('a'.repeat(32),a,b),lanes.receiptDigest('a'.repeat(32),c,d));console.log('2 delimiterPairs=4 distinct');
const facts={sha256:'f'.repeat(64),nonce:'a'.repeat(32),channel:'a}文'};for(const ch of ['', 'a}b','文', 'x'.repeat(1000000)])assert.equal(lanes.decodeReceiptFacts(lanes.encodeReceiptFacts({...facts,channel:ch})).channel,ch);
for(const raw of ['{','null','{"channel":{}}'])assert.equal(lanes.decodeReceiptFacts('receipt='+raw.length+':'+raw),null);
const raw=JSON.stringify(facts).slice(0,-1)+',"channel":"last","__proto__":{"polluted":true},"constructor":{"x":1}}';const parsed=lanes.decodeReceiptFacts('receipt='+raw.length+':'+raw);assert.equal(parsed.channel,'last');assert.equal({}.polluted,undefined);console.log('3 malformed=3 refused roundtrips=4 duplicate=last-wins pollution=false');
(async()=>{for(const mode of ['hidden-ancestor','throw-recheck','detach-digest','detach-value-get']){let acks=0,refresh=0;const doc={};let phase=false;const box={value:'',isConnected:true,ownerDocument:doc,hidden:false,parentElement:{hidden:true},dispatchEvent(){}};const state={pending:[],current:{}};const r={lanes:[{id:'x'}],bundle:'RESULT-X',receipt:{bytes:8,nonce:'n',channel:'composer'}};const c=vm.createContext({document:doc,TextEncoder,node:{prompt:box},state,Event:class{},console:{info(){}},saveDraft(){},renderPending(){},refreshPending:async()=>refresh++,sha256Hex:async()=>{if(mode==='detach-digest')box.isConnected=false;if(mode==='throw-recheck')Object.defineProperty(box,'isConnected',{get(){throw Error('recheck')}});if(mode==='detach-value-get'){const v=box.value;Object.defineProperty(box,'value',{get(){box.isConnected=false;return v}})}return 'hash'},api:{processLanes:async()=>r,ackLanes:async()=>{acks++;return {}}}});const app=src('public/app.js');vm.runInContext(app.slice(app.indexOf('async function processPending('),app.indexOf('/** SubtleCrypto sha256')),c);vm.runInContext(app.slice(app.indexOf('function showPendingBundle('),app.indexOf('async function dismissPending(')),c);let rejected=false;try{await c.processPending(['x'])}catch{rejected=true}console.log('4 '+mode+' '+JSON.stringify({acks,refresh,rejected,problem:!!state.pendingActionProblem}));}fs.writeFileSync('/tmp/arch017-r7-evidence.json',JSON.stringify(lanes.readAll(),null,2));})();
