const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const {stripTypeScriptTypes}=require('module');
const root=process.cwd(),tmp=fs.mkdtempSync('/tmp/a17-r6-');
function src(f){return fs.readFileSync(path.join(root,f),'utf8')}
function strip(s){return stripTypeScriptTypes(s).replace(/^import .*;\s*$/mg,'').replace(/\bexport /g,'')}
let l=strip(src('src/server/lanes.ts')); l=l.replace(/function assertWriter\(\)\s*\{[\s\S]*?\n\}/,'function assertWriter() {}');
const ctx=vm.createContext({fs,path,net:{},createHash:crypto.createHash,randomBytes:crypto.randomBytes,process,Buffer,console,dataDir:()=>tmp,ensureDir:p=>fs.mkdirSync(p,{recursive:true}),writeAtomic:(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)}});
vm.runInContext(l,ctx);const lanes={};for(const m of l.matchAll(/function (\w+)\(/g))lanes[m[1]]=ctx[m[1]]; Object.assign(lanes,{GROUP_CLOSE_TTL_MS:300000,HELD_STARVATION_MS:300000});
const dc=vm.createContext({lanes,crypto,Buffer,console});vm.runInContext(strip(src('src/server/lane-drain.ts')),dc);
function add(g,id,open=false){lanes.recordDispatch({groupId:g,groupOpen:open,groupSize:2,label:id,charter:'qa',provider:'qa',transport:'socket'},id);lanes.settle(id,{state:'settled',resultText:'RESULT '+id})}
add('seal','a',true);let out=dc.process(['lane:a']);let refused=false;try{add('seal','b',true)}catch(e){refused=e.code||e.message.split(':')[0]};console.log('1 seal',JSON.stringify({sent:out.lanes.length,sealed:!!lanes.groupState('seal').sealed,open:lanes.groupState('seal').open,terminal:dc.groupTerminal('seal').terminal,lateRefused:!!refused}));
lanes.openGroup('seal',{members:[{label:'bypass',charter:'qa',provider:'qa',transport:'socket'}]});console.log('1 bypass members='+lanes.groupState('seal').members+' sealed='+!!lanes.groupState('seal').sealed);
for(const [i,ch] of ['composer/main','a"b','a\nb','文','', 'a}b'].entries()){add('c'+i,'c'+i);const b=dc.process(['group:c'+i],{channel:ch});const a=dc.acknowledge(['c'+i],{...b.receipt,digest:b.receipt.digest.toUpperCase()});console.log('2 channel',JSON.stringify(ch),'sent='+b.lanes.length+' ack='+a.acknowledged.length);assert.equal(b.lanes.length,1)}
add('fail','f1');add('fail','f2');const original=lanes.restampHandoff;let fail=true;lanes.restampHandoff=(...a)=>{if(fail)throw Error('injected disk failure');return original(...a)};const bad=dc.process(['group:fail']);fail=false;const good=dc.process(['group:fail']);const ack=dc.acknowledge(good.lanes.map(x=>x.id),good.receipt);console.log('3 retry',JSON.stringify({refusedBytes:bad.receipt.bytes,skipped:bad.skipped.length,retrySent:good.lanes.length,acked:ack.acknowledged.length}));assert.equal(ack.acknowledged.length,2);
(async()=>{for(const mode of ['detached','hidden','foreign','replace-on-input','replace-during-digest']){let acks=0,refresh=0;const box={value:'',isConnected:mode!=='detached',hidden:mode==='hidden',ownerDocument:mode==='foreign'?{}:null,dispatchEvent(){if(mode==='replace-on-input')this.isConnected=false}};const state={pending:[],current:{}};const r={lanes:[{id:'x'}],bundle:'RESULT-X',receipt:{bytes:8,nonce:'n',channel:'composer'}};const c=vm.createContext({node:{prompt:box},state,Event:class{},console:{info(){}},saveDraft(){},renderPending(){},refreshPending:async()=>refresh++,sha256Hex:async()=>{if(mode==='replace-during-digest')box.isConnected=false;return 'hash'},api:{processLanes:async()=>r,ackLanes:async()=>{acks++;return {}}}});vm.runInContext(src('public/app.js').slice(src('public/app.js').indexOf('async function processPending('),src('public/app.js').indexOf('/** SubtleCrypto sha256')),c);vm.runInContext(src('public/app.js').slice(src('public/app.js').indexOf('function showPendingBundle('),src('public/app.js').indexOf('async function dismissPending(')),c);await c.processPending(['x']);console.log('4',mode,JSON.stringify({acks,refresh,connected:box.isConnected,error:!!state.pendingActionProblem}));}
fs.writeFileSync('/tmp/arch017-r6-evidence.json',JSON.stringify(lanes.readAll(),null,2));})();
