const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const {stripTypeScriptTypes}=require('module');
const root=process.cwd(); const src=f=>fs.readFileSync(path.join(root,f),'utf8');
const strip=s=>stripTypeScriptTypes(s).replace(/^import .*;\s*$/mg,'').replace(/\bexport /g,'');
function env(mutate=s=>s){const tmp=fs.mkdtempSync('/tmp/a17-r8-');let l=strip(src('src/server/lanes.ts')).replace(/function assertWriter\(\)\s*\{[\s\S]*?\n\}/,'function assertWriter() {}'); const ctx=vm.createContext({fs,path,net:{},createHash:crypto.createHash,randomBytes:crypto.randomBytes,process,Buffer,console,dataDir:()=>tmp,ensureDir:p=>fs.mkdirSync(p,{recursive:true}),writeAtomic:(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)}});vm.runInContext(l,ctx);const lanes={};for(const m of l.matchAll(/function (\w+)\(/g))lanes[m[1]]=ctx[m[1]];for(const k of ['GROUP_CLOSE_TTL_MS','HELD_STARVATION_MS'])lanes[k]=vm.runInContext(k,ctx);const dc=vm.createContext({lanes,crypto,Buffer,console});vm.runInContext(strip(mutate(src('src/server/lane-drain.ts'))),dc);const add=(g,id,extra={})=>lanes.recordDispatch({groupId:g,label:id,charter:'qa',provider:'qa',transport:'socket',...extra},id);const done=id=>lanes.settle(id,{state:'settled',resultText:'RESULT '+id});return {lanes,dc,add,done,tmp};}
{
 const {lanes,dc,add,done}=env(); add('g','a',{groupOpen:true,at:1});add('g','b',{groupOpen:true});done('a');let b=dc.process(['lane:a']);assert.equal(dc.acknowledge(['a'],b.receipt).acknowledged.length,1);assert.equal(lanes.groupState('g').sealedKind,'drained');for(let i=0;i<59;i++)add('fill'+i,'fill'+i);assert.equal(lanes.get('a'),null);const seal=lanes.groupState('g').sealedKind;add('g','late');assert.equal(lanes.get('late').groupId,'g');console.log('seal after pruning acknowledged sibling='+seal+' lateJoin=accepted');
 lanes.dismiss(['b','late']); for(let i=59;i<62;i++)add('fill'+i,'fill'+i);assert.equal(lanes.groupState('g').members,0);add('g','reborn');done('reborn');const second=dc.process(['group:g']);assert.equal(second.lanes.length,1);console.log('all rows pruned: identity reused=true secondDrain='+second.lanes.length);
}
{
 const {lanes,dc,add,done}=env();add('g','a');add('g','b');done('a');done('b');const original=lanes.restampHandoff;lanes.restampHandoff=(id,...args)=>{if(id==='b')throw Error('power loss');return original(id,...args)};const first=dc.process(['group:g']);assert.equal(first.lanes.length,1);lanes.restampHandoff=original;const retry=dc.process(['group:g']);assert.equal(dc.acknowledge(['a','b'],retry.receipt).acknowledged.length,2);console.log('partial write recovery: first=1 retry=2 acknowledged=2');
}
{
 const {lanes,dc,add,done}=env();add('g','a');done('a');const original=lanes.restampHandoff;lanes.restampHandoff=(id,...args)=>{fs.writeFileSync(lanes.laneStoreFile(),'[]');add('replacement',id);lanes.settle(id,{state:'settled',resultText:'UNSEEN REPLACEMENT RESULT'});return original(id,...args)};const out=dc.process(['group:g']);const ack=dc.acknowledge(['a'],out.receipt);assert.equal(lanes.get('a').groupId,'replacement');assert.equal(ack.acknowledged.length,1);assert.equal(out.bundle.includes('UNSEEN REPLACEMENT RESULT'),false);console.log('ledger replaced mid-drain: replacementGroup='+lanes.get('a').groupId+' acknowledgedByOldBundle='+ack.acknowledged.length);
}
{
 const {lanes,dc,add}=env();add('g','a',{groupOpen:true});lanes.extendGroup('g',Number.MAX_VALUE,Number.MAX_VALUE);const row=JSON.parse(fs.readFileSync(lanes.laneStoreFile()))[0];assert.equal(row.groupCloseDeadline,null);assert.equal(dc.sweep(Number.MAX_VALUE).closed.length,0);console.log('finite deadline addition overflow: diskDeadline='+row.groupCloseDeadline+' sweepClosed=0 open='+lanes.groupState('g').open);
}
{
 const {lanes,dc}=env(s=>s.replace('const starved = waited >= lanes.HELD_STARVATION_MS;','const starved = waited >= lanes.HELD_STARVATION_MS && waited < 2 * lanes.HELD_STARVATION_MS;'));
 const suite=src('scripts/verify-arch-017-drain.mjs');const block=suite.slice(suite.indexOf("check('H4 —"),suite.indexOf("check('H5 —"));let passes=0;const c=vm.createContext({lanes,drain:dc,assert,process,project:{id:'qa'},show(){},check(n,fn){fn();passes++}});vm.runInContext(block,c);const r=lanes.list({groupId:'g-starve'}).find(r=>r.label==='quick');const p=dc.pending({now:r.settledAt+2*lanes.HELD_STARVATION_MS,sweepFirst:false}).find(x=>x.groupId==='g-starve');assert.equal(p.ready,false);console.log('starvation mutant: production H4 assertions PASS='+passes+' readyAt40min='+p.ready);
}
async function ui(mode){let resolve,acks=0,refresh=0;const doc={};const box={value:'',isConnected:true,ownerDocument:doc,parentElement:mode==='css'?{style:{display:'none'},hidden:false}:null,dispatchEvent(){}};const state={pending:[{id:'group:g'}],current:{id:'A',projectId:'A'}};const response={lanes:[{id:'a'}],bundle:'PROJECT A RESULT',receipt:{bytes:16,nonce:'n',channel:'composer'}};const c=vm.createContext({document:doc,TextEncoder,node:{prompt:box},state,Event:class{},console:{info(){}},saveDraft(){},renderPending(){},refreshPending:async()=>refresh++,sha256Hex:async()=>{if(mode==='digest-fails')throw Error('digest unavailable');return 'hash'},api:{processLanes:()=>new Promise(r=>resolve=r),ackLanes:async()=>{acks++;return {}}}});const app=src('public/app.js');vm.runInContext(app.slice(app.indexOf('async function processPending('),app.indexOf('/** SubtleCrypto sha256')),c);vm.runInContext(app.slice(app.indexOf('function showPendingBundle('),app.indexOf('async function dismissPending(')),c);const pending=c.processPending(['group:g']);if(mode==='switch')state.current={id:'B',projectId:'B'};resolve(response);let escaped=false;try{await pending}catch{escaped=true}assert.equal(box.value.includes(response.bundle),true);if(mode==='digest-fails'){assert.equal(acks,0);assert.equal(refresh,0);assert.equal(escaped,true)}else{assert.equal(acks,1);assert.equal(state.pendingActionProblem,null)}console.log('rail '+mode+': '+JSON.stringify({acks,refresh,escaped,destination:state.current.id,contains:box.value.includes(response.bundle),problem:!!state.pendingActionProblem}));}
(async()=>{await ui('switch');await ui('css');await ui('digest-fails')})();
{
 const mut=src('scripts/verify-arch-017-mutation.mjs');const head=mut.slice(mut.indexOf('const DRAIN ='),mut.indexOf('/*\n * ROUND 7 — OPTIONAL SUITE FILTER'));
 const mutants=new Function(head+';return MUTANTS')();let ambiguous=0,missing=0;for(const m of mutants){let s=src(m.file);for(const [from,to]of m.edits){const n=s.split(from).length-1;if(n!==1){console.log('anchor '+m.id+' count='+n+' '+JSON.stringify(from.slice(0,70)));if(n===0)missing++;else ambiguous++;}s=s.replace(from,to)}}console.log('harness anchor audit: mutants='+mutants.length+' missing='+missing+' ambiguous='+ambiguous);
}
{
 const {lanes,dc,add,done}=env();add('g','a',{groupOpen:true});add('g','b',{groupOpen:true});done('a');const t=lanes.get('a').settledAt+lanes.HELD_STARVATION_MS;const before=dc.pending({now:t,sweepFirst:false})[0].ready;const after=dc.pending({now:t-3600000,sweepFirst:false})[0].ready;assert.equal(before,true);assert.equal(after,false);console.log('clock rollback 1h: ready='+before+' -> '+after);
 lanes.extendGroup('g',-1);assert.equal(dc.sweep().closed.includes('g'),true);console.log('negative deadline: expired group closes=true');
}
