const base=require('fs').readFileSync('scripts/reviewers/arch017-r9.cjs','utf8');
eval(base.slice(0,base.indexOf('const mode=')).replace('function env(', 'globalThis.env=function env(').replace('return {tmp,ctx,lanes','return {tmp,ctx,lanes'));
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const mode=process.argv[2];
if(mode==='seals'){
 const e=env(); e.add('g','a');e.done('a');fs.writeFileSync(e.tmp+'/group-seals.json','{"g":false}');assert.equal(e.lanes.durableGroupSeal('g'),null);e.add('g','b');console.log('malformed entry false: late admission accepted');
 fs.writeFileSync(e.tmp+'/group-seals.json','{');for(let i=0;i<3;i++){assert.equal(e.dc.process(['lane:a']).lanes.length,0)}assert.equal(fs.readFileSync(e.tmp+'/group-seals.json','utf8'),'{');fs.writeFileSync(e.tmp+'/group-seals.json','{}');assert.equal(e.dc.process(['lane:a']).lanes.length,1);console.log('corruption: 3 retries blocked; manual repair restores delivery');
}
if(mode==='retry'){
 const e=env();e.add('g','a');e.done('a');const {stripTypeScriptTypes}=require('module');let s=fs.readFileSync('src/server/dispatch-broker.ts','utf8');s=stripTypeScriptTypes(s.slice(s.indexOf('function terminal('),s.indexOf('\nfunction ',s.indexOf('function terminal(')+1))).replace(/export /g,'');const c=vm.createContext({lanes:e.lanes,Buffer,receiptDigest:(n,fd,p)=>e.lanes.receiptDigest(n,'fd'+fd,p)});vm.runInContext(s,c);assert.throws(()=>c.terminal({destroyed:false,end(){throw Error('EPIPE')}},{ok:true,text:'RESULT a'},()=>{},false,()=>{},()=>e.lanes.sealGroupDurably('g','drained','test')),/EPIPE/);assert.ok(e.lanes.durableGroupSeal('g'));assert.equal(e.lanes.get('a').acknowledgedAt,null);const out=e.dc.process(['group:g']);assert.equal(out.lanes.length,1);console.log('sealed broker EPIPE: held=true rail retry=1');const retry=e.dc.process(['group:g']);assert.equal(retry.lanes.length,1);console.log('discarded rail response: retry=1');
}
if(mode==='legacy'){
 const e=env();e.ctx.isWriter=()=>true;e.add('g','a');e.add('h','b');let rows=e.lanes.readAll();rows.forEach(r=>delete r.generation);fs.writeFileSync(e.lanes.laneStoreFile(),JSON.stringify(rows));const atomic=e.ctx.writeAtomic;e.ctx.writeAtomic=(p,s)=>{if(p===e.lanes.laneStoreFile())throw Error('ENOSPC');return atomic(p,s)};const failed=e.lanes.readAll();assert.ok(failed[0].generation);assert.equal(JSON.parse(fs.readFileSync(e.lanes.laneStoreFile()))[0].generation,undefined);e.ctx.writeAtomic=atomic;const good=e.lanes.readAll();assert.notEqual(good[0].generation,failed[0].generation);assert.notEqual(good[0].generation,good[1].generation);assert.equal(e.lanes.readAll()[0].generation,good[0].generation);console.log('upgrade ENOSPC: disk unchanged; retry persists distinct stable 96-bit generations');
}
if(mode==='retention'){
 const e=env();const seals={};for(let i=0;i<50000;i++)seals['g'+i]={at:1000+i,kind:'drained',why:'test'};fs.writeFileSync(e.tmp+'/group-seals.json',JSON.stringify(seals));e.lanes.sealGroupDurably('new','drained','clock rollback',1);const after=JSON.parse(fs.readFileSync(e.tmp+'/group-seals.json'));assert.equal(Object.keys(after).length,50000);assert.equal(after.new,undefined);console.log('50000 boundary + clock rollback: newly sealed group immediately evicted');console.log('default ID sample='+e.lanes.newLaneId(1)+'; random suffix <=6 base36 chars (~31 bits), Math.random');
}
if(mode==='ack'){
 const e=env();e.add('g','a');e.done('a');const out=e.dc.process(['group:g']);const ack=e.dc.acknowledge(['a'],JSON.parse(JSON.stringify(out.receipt)));assert.equal(ack.acknowledged.length,1);assert.ok(JSON.parse(fs.readFileSync(e.lanes.laneStoreFile()))[0].acknowledgedAt);console.log('echo server receipt; consumer emits 0 bytes; disk acknowledged=true');
}
if(mode==='session')(async()=>{for(const variant of ['absent','directory','recreated']){let resolve,acks=0;const doc={},box={value:'',isConnected:true,ownerDocument:doc,dispatchEvent(){}};const initial={sessionId:variant==='absent'?null:'A',projectId:'P',encodedDir:'dir1'};const state={pending:[{id:'group:g'}],current:initial};const c=vm.createContext({document:doc,TextEncoder,node:{prompt:box},state,Event:class{},console:{info(){}},saveDraft(){},renderPending(){},refreshPending:async()=>{},sha256Hex:async()=> 'hash',api:{processLanes:()=>new Promise(r=>resolve=r),ackLanes:async()=>{acks++;return {}}}});const app=fs.readFileSync('public/app.js','utf8');vm.runInContext(app.slice(app.indexOf('async function processPending('),app.indexOf('/** SubtleCrypto sha256')),c);vm.runInContext(app.slice(app.indexOf('function showPendingBundle('),app.indexOf('async function dismissPending(')),c);const p=c.processPending(['group:g']);state.current={...initial,encodedDir:variant==='directory'?'dir2':initial.encodedDir};resolve({lanes:[{id:'a'}],bundle:'PRIVATE RESULT',receipt:{bytes:14,nonce:'n',channel:'composer'}});await p;assert.equal(acks,1);console.log(variant+': changed destination object; result inserted=true ack=1')}})();
