#!/usr/bin/env node
import { spawn } from 'node:child_process';
import * as fs from 'node:fs';
import * as net from 'node:net';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2); const opts = { provider: null, model: null, sandbox: null, timeoutMin: null, ticket: null, phase: null, round: null, class: null, stdin: false, check: false }; const prompt = [];
const take = (i, flag) => { if (i + 1 >= args.length) throw new Error(`${flag} needs a value`); return args[i + 1]; };
try { for (let i = 0; i < args.length; i++) { const a = args[i]; if (a === '--check') opts.check = true; else if (a === '--prompt-stdin') opts.stdin = true; else if (['--provider','--model','--sandbox','--timeout-min','--ticket','--phase','--round','--class'].includes(a)) { const key = a === '--timeout-min' ? 'timeoutMin' : a.slice(2); opts[key] = take(i, a); i++; } else if (a.startsWith('--')) throw new Error(`unknown flag ${a}`); else prompt.push(a); } } catch (e) { process.stderr.write(`${e.message}\n`); process.exit(2); }
const socketPath = process.env.ORCHARD_DISPATCH_SOCK;
const here = path.dirname(fileURLToPath(import.meta.url));
const checkoutScript = path.resolve(here, '..', '..', 'scripts', 'dispatch.mjs');

function direct(argv, body) { const c = spawn(process.execPath, [checkoutScript, ...argv], { stdio: ['pipe', 'inherit', 'inherit'] }); c.stdin.end(body); c.on('exit', (code) => process.exit(code ?? 1)); c.on('error', (e) => { process.stderr.write(`dispatch failed [transport] ${e.message}\n`); process.exit(1); }); }
function unavailable(reason, action = 'enable settings.tools.openaiDispatch for this project and launch a new session') { process.stdout.write(`openai dispatch: unavailable\nroute: none\nreason: ${reason}\naction: ${action}\n`); process.exit(1); }
function socketRequest(req, check) { const s = net.createConnection(socketPath); let buf = ''; let terminal = false; s.setEncoding('utf8'); s.on('connect', () => s.write(`${JSON.stringify(req)}\n`)); s.on('data', (chunk) => { buf += chunk; for (;;) { const n = buf.indexOf('\n'); if (n < 0) break; const line = buf.slice(0,n); buf = buf.slice(n+1); let f; try { f=JSON.parse(line); } catch { continue; } if (check) { process.stdout.write(`openai dispatch: ${f.ok && f.entitled ? 'available' : 'unavailable'}\nroute: host broker unix socket ${socketPath}\nproviders: ${(f.providers||[]).join(',') || 'none'}\nmodels: ${JSON.stringify(f.models||{})}\ncommand: ${f.dispatchCmd || process.env.ORCHARD_DISPATCH_CMD || 'node /opt/orchard-dispatch/dispatch-client.mjs'}\n`); terminal=true; s.end(); process.exit(f.ok && f.entitled ? 0 : 1); } if (f.op === 'progress') process.stderr.write(f.text); if (f.op === 'result') { terminal=true; if (f.ok) process.stdout.write(f.text); else process.stderr.write(`dispatch failed [${f.failureKind || 'internal'}] ${f.text || 'host broker failed'}\n`); s.end(); process.exit(f.ok ? 0 : (f.exitCode || 1)); } } }); s.on('error', (e) => check ? unavailable(`broker socket cannot be reached: ${e.message}`) : (process.stderr.write(`dispatch failed [transport] ${e.message}\n`), process.exit(1))); s.on('close', () => { if (!terminal) { process.stderr.write('dispatch failed [transport] broker closed without a terminal frame\n'); process.exit(1); } }); }

if (opts.check) { if (process.env.ORCHARD_DISPATCH_ENTITLED === '0') unavailable('this session was launched with settings.tools.openaiDispatch disabled'); else if (process.env.ORCHARD_DISPATCH_UNAVAILABLE_REASON) unavailable(process.env.ORCHARD_DISPATCH_UNAVAILABLE_REASON, 'fix the reported host broker failure and launch a new session'); else if (socketPath) socketRequest({ op:'capabilities' }, true); else if (fs.existsSync(checkoutScript)) { process.stdout.write(`openai dispatch: available\nroute: direct host checkout\nproviders: openai\nmodels: provider default or --model\ncommand: node ${fileURLToPath(import.meta.url)}\n`); process.exit(0); } else unavailable('no broker socket and the Orchard checkout is not readable'); }
else { let body = prompt.join(' ').trim(); if (opts.stdin) { if (body) { process.stderr.write('dispatch failed [invalid-request] --prompt-stdin and positional prompt are mutually exclusive\n'); process.exit(2); } body=fs.readFileSync(0,'utf8'); } if (!body.trim()) { process.stderr.write('dispatch failed [invalid-request] no prompt given\n'); process.exit(2); } if (!opts.provider) opts.provider='openai'; if (socketPath) socketRequest({ op:'dispatch', provider:opts.provider, ...(opts.model?{model:opts.model}:{}), ...(opts.sandbox?{sandbox:opts.sandbox}:{}), ...(opts.timeoutMin?{timeoutMin:Number(opts.timeoutMin)}:{}), ...(opts.ticket?{ticket:opts.ticket}:{}), ...(opts.phase?{phase:opts.phase}:{}), ...(opts.round?{round:opts.round}:{}), ...(opts.class?{class:opts.class}:{}), prompt:body }, false); else if (fs.existsSync(checkoutScript)) { const av=['--provider',opts.provider,'--prompt-stdin']; for (const [k,f] of [['model','--model'],['sandbox','--sandbox'],['timeoutMin','--timeout-min'],['ticket','--ticket'],['phase','--phase'],['round','--round'],['class','--class']]) if(opts[k]) av.push(f,String(opts[k])); direct(av,body); } else unavailable('no broker socket and the Orchard checkout is not readable'); }
